// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.miniprojet.messaging;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string sender_id = 2;</code>
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiver_id = 3;</code>
   */
  java.lang.String getReceiverId();
  /**
   * <code>string receiver_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string message_text = 4;</code>
   */
  java.lang.String getMessageText();
  /**
   * <code>string message_text = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageTextBytes();
}
