// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messaging.proto

package com.miniprojet.messaging;

public interface MessagesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessagesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Message messages = 1;</code>
   */
  java.util.List<com.miniprojet.messaging.Message> 
      getMessagesList();
  /**
   * <code>repeated .Message messages = 1;</code>
   */
  com.miniprojet.messaging.Message getMessages(int index);
  /**
   * <code>repeated .Message messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .Message messages = 1;</code>
   */
  java.util.List<? extends com.miniprojet.messaging.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .Message messages = 1;</code>
   */
  com.miniprojet.messaging.MessageOrBuilder getMessagesOrBuilder(
      int index);
}
